# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [23]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [24]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [25]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [26]:
img

array([[3, 8, 7, 1, 2, 4, 4, 7, 6, 4, 7, 0],
       [5, 4, 2, 6, 9, 8, 2, 8, 0, 5, 6, 7],
       [3, 6, 9, 7, 2, 7, 4, 9, 2, 9, 6, 1],
       [9, 4, 2, 8, 8, 3, 0, 2, 1, 4, 5, 3],
       [6, 7, 2, 9, 2, 5, 3, 2, 7, 9, 0, 4],
       [6, 1, 1, 3, 7, 6, 5, 1, 5, 1, 4, 0],
       [9, 7, 4, 7, 7, 5, 6, 4, 8, 3, 9, 1],
       [5, 2, 1, 9, 1, 5, 4, 6, 0, 6, 3, 8],
       [0, 1, 9, 4, 2, 7, 7, 9, 6, 4, 5, 4],
       [1, 0, 8, 8, 4, 5, 0, 2, 0, 5, 4, 8],
       [9, 5, 1, 3, 9, 2, 6, 6, 7, 2, 1, 1],
       [5, 7, 6, 4, 7, 6, 9, 8, 3, 0, 4, 9]])

In [27]:
h,w=img.shape

In [28]:
print(h,w)

12 12


In [29]:
#[*range(-2,3)]

In [30]:
dst = np.zeros((h,w),np.int)

/var/folders/qs/kpr107616cncng7n99zy3t480000gn/T/ipykernel_4124/2160328971.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [31]:
l=1
kernel = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]],np.float32)

In [32]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [33]:
img

array([[3, 8, 7, 1, 2, 4, 4, 7, 6, 4, 7, 0],
       [5, 4, 2, 6, 9, 8, 2, 8, 0, 5, 6, 7],
       [3, 6, 9, 7, 2, 7, 4, 9, 2, 9, 6, 1],
       [9, 4, 2, 8, 8, 3, 0, 2, 1, 4, 5, 3],
       [6, 7, 2, 9, 2, 5, 3, 2, 7, 9, 0, 4],
       [6, 1, 1, 3, 7, 6, 5, 1, 5, 1, 4, 0],
       [9, 7, 4, 7, 7, 5, 6, 4, 8, 3, 9, 1],
       [5, 2, 1, 9, 1, 5, 4, 6, 0, 6, 3, 8],
       [0, 1, 9, 4, 2, 7, 7, 9, 6, 4, 5, 4],
       [1, 0, 8, 8, 4, 5, 0, 2, 0, 5, 4, 8],
       [9, 5, 1, 3, 9, 2, 6, 6, 7, 2, 1, 1],
       [5, 7, 6, 4, 7, 6, 9, 8, 3, 0, 4, 9]])

In [34]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  -1, -16,  11,  27,  18, -14,  22, -21,   6,   5,   0],
       [  0,  10,  28,  10, -21,  18,   2,  29,  -9,  28,   9,   0],
       [  0,  -4, -13,  14,  25,  -5, -12,  -2, -10,  -4,  12,   0],
       [  0,  22,  -9,  30, -19,  11,   3,  -3,  18,  33, -22,   0],
       [  0, -16,  -5,  -9,  17,   8,   9, -11,   8, -16,  10,   0],
       [  0,  19,   4,  12,  15,   1,  12,  -1,  28,  -9,  34,   0],
       [  0,  -4, -19,  32, -18,   8,  -4,  13, -26,  20, -13,   0],
       [  0,  -6,  31,  -8,  -6,  16,  15,  24,  17,  -2,  10,   0],
       [  0, -15,  22,  21,  -4,  12, -20,  -5, -20,  15,   1,   0],
       [  0,   8, -17,  -7,  29, -16,  13,   7,  24,  -3,  -6,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [35]:
img = cv2.imread('lena.png', 0)

In [36]:
h,w=img.shape

In [37]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [38]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [39]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1